-- V19: Demo data seed for customer presentation
-- Adds 5 additional staff accounts (total 7), checklists per zone, and shift assignments.
-- Idempotent: safe to run on top of any existing data.

-- ---------------------------------------------------------------------------
-- Additional staff accounts (5 more for total of 7 staff + 1 admin)
-- Passwords: 'staff123' for all staff accounts (BCrypt generated by AdminBootstrap)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO users (id, username, password_hash, full_name, role, status, lang)
VALUES
    (3, 'nhanvien02', '__STAFF_BCRYPT__', 'Nguyễn Văn A',    'STAFF', 'ACTIVE', 'vi'),
    (4, 'nhanvien03', '__STAFF_BCRYPT__', 'Trần Thị B',      'STAFF', 'ACTIVE', 'vi'),
    (5, 'nhanvien04', '__STAFF_BCRYPT__', 'Lê Văn C',        'STAFF', 'ACTIVE', 'ko'),
    (6, 'nhanvien05', '__STAFF_BCRYPT__', 'Phạm Thị D',      'STAFF', 'ACTIVE', 'vi'),
    (7, 'nhanvien06', '__STAFF_BCRYPT__', 'Hoàng Văn E',     'STAFF', 'ACTIVE', 'vi');

-- ---------------------------------------------------------------------------
-- Checklists: 1 per zone (BEP_PHO, BUN_CHA, PHUC_VU, KHO)
-- 10 tasks each, mix of required and optional.
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO checklists (id, zone_id, sort_order) VALUES
    (1, 1, 1),  -- Bếp phở
    (2, 2, 1),  -- Bún chả
    (3, 3, 1),  -- Phục vụ
    (4, 4, 1);  -- Kho

INSERT OR IGNORE INTO checklist_translations (checklist_id, language_code, title, description) VALUES
    (1, 'vi', 'Checklist mở ca - Bếp phở',  'Các công việc cần làm khi bắt đầu ca'),
    (1, 'ko', '오픈 체크리스트 - 쌀국수 주방', '시작 시 해야 할 일들'),
    (2, 'vi', 'Checklist mở ca - Bún chả',  'Các công việc cần làm khi bắt đầu ca'),
    (2, 'ko', '오픈 체크리스트 - 분짜',       '시작 시 해야 할 일들'),
    (3, 'vi', 'Checklist mở ca - Phục vụ',  'Các công việc cần làm khi bắt đầu ca'),
    (3, 'ko', '오픈 체크리스트 - 홀 서빙',   '시작 시 해야 할 일들'),
    (4, 'vi', 'Checklist mở ca - Kho',      'Các công việc cần làm khi bắt đầu ca'),
    (4, 'ko', '오픈 체크리스트 - 창고',       '시작 시 해야 할 일들');

-- ---------------------------------------------------------------------------
-- Tasks: 10 per checklist (Zone 1 - Bếp phở)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO checklist_tasks (id, checklist_id, is_required, sort_order) VALUES
    ( 1, 1, 1, 1),  ( 2, 1, 1, 2),  ( 3, 1, 1, 3),  ( 4, 1, 0, 4),  ( 5, 1, 1, 5),
    ( 6, 1, 1, 6),  ( 7, 1, 1, 7),  ( 8, 1, 0, 8),  ( 9, 1, 1, 9),  (10, 1, 1, 10);

INSERT OR IGNORE INTO checklist_task_translations (task_id, language_code, title, description) VALUES
    ( 1, 'vi', 'Kiểm tra nước dùng',         'Đảm bảo nước dùng đã sôi và có mùi thơm'),
    ( 1, 'ko', '육수 확인',                  '육수가 끓고 향이 나는지 확인'),
    ( 2, 'vi', 'Chuẩn bị bánh phở',         'Cắt bánh phở và ngâm nước lạnh'),
    ( 2, 'ko', '쌀국수 준비',                '쌀국수 자르고 찬물에 담그기'),
    ( 3, 'vi', 'Sơ chế thịt bò',            'Rửa sạch và thái mỏng thịt bò'),
    ( 3, 'ko', '소고기 준비',                '소고기 씻고 얇게 썰기'),
    ( 4, 'vi', 'Pha nước mắm chấm',        'Chuẩn bị chén nước mắm ớt'),
    ( 4, 'ko', '너겟 소스 준비',             '고추 너겟 그릇 준비'),
    ( 5, 'vi', 'Bật bếp và đun sôi',       'Bật tất cả bếp gas, đun nước sôi'),
    ( 5, 'ko', '불 켜고 끓이기',             '가스불 켜고 물 끓이기'),
    ( 6, 'vi', 'Chuẩn bị rau thơm',         'Rửa sạch hành, ngò, rau thơm'),
    ( 6, 'ko', '향신채 준비',                '양파, 고수 등 씻기'),
    ( 7, 'vi', 'Vệ sinh khu vực bếp',       'Lau sạch bàn, sàn khu vực bếp'),
    ( 7, 'ko', '주방 청소',                  '조리대, 바닥 닦기'),
    ( 8, 'vi', 'Kiểm tra tủ lạnh',         'Đảm bảo tủ lạnh hoạt động bình thường'),
    ( 8, 'ko', '냉장고 확인',                '냉장고 정상 작동 확인'),
    ( 9, 'vi', 'Chuẩn bị đồ dùng phục vụ',  'Đếm đủ bát, đĩa, đũa'),
    ( 9, 'ko', '서빙 도구 준비',             '그릇, 접시, 젓가락 충분한지 확인'),
    (10, 'vi', 'Mặc đồng phục và khẩu trang', 'Đảm bảo đồng phục sạch, khẩu trang đeo đúng'),
    (10, 'ko', '유니폼과 마스크 착용',       '깨끗한 유니폼, 마스크 올바르게 착용');

-- ---------------------------------------------------------------------------
-- Tasks: 10 per checklist (Zone 2 - Bún chả)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO checklist_tasks (id, checklist_id, is_required, sort_order) VALUES
    (11, 2, 1, 1),  (12, 2, 1, 2),  (13, 2, 1, 3),  (14, 2, 1, 4),  (15, 2, 0, 5),
    (16, 2, 1, 6),  (17, 2, 1, 7),  (18, 2, 1, 8),  (19, 2, 0, 9),  (20, 2, 1, 10);

INSERT OR IGNORE INTO checklist_task_translations (task_id, language_code, title, description) VALUES
    (11, 'vi', 'Chuẩn bị than',             'Đổ than vào lò, nhóm lửa'),
    (11, 'ko', '숯 준비',                    '숯을 화로에 넣고 불 붙이기'),
    (12, 'vi', 'Ướp thịt heo',              'Kiểm tra thịt đã ướp đủ gia vị'),
    (12, 'ko', '돼지고기 양념',              '양념이 잘 베이게 확인'),
    (13, 'vi', 'Chuẩn bị bún',              'Trụng bún và để ráo'),
    (13, 'ko', '분 준비',                    '분 데치고 물기 제거'),
    (14, 'vi', 'Pha nước chấm',            'Pha nước mắm chua ngọt'),
    (14, 'ko', '소스 만들기',                '새콤달콤 너겟 만들기'),
    (15, 'vi', 'Kiểm tra rau sống',         'Đảm bảo đủ rau sống các loại'),
    (15, 'ko', '생채소 확인',                '각종 생채소 충분한지 확인'),
    (16, 'vi', 'Bật lò nướng',              'Bật lò nướng và chờ nóng'),
    (16, 'ko', '그릴 켜기',                  '그릴 켜고 달궈지기 기다리기'),
    (17, 'vi', 'Chuẩn bị chả',              'Nặn chả thịt và chả mọc sẵn'),
    (17, 'ko', '패티 준비',                  '고기 패티와 새우 패티 빚기'),
    (18, 'vi', 'Vệ sinh khu vực nướng',     'Lau sạch bàn nướng và hút mỡ'),
    (18, 'ko', '그릴 구역 청소',             '그릴 테이블 닦고 기름기 제거'),
    (19, 'vi', 'Kiểm tra gas',              'Đảm bảo van gas an toàn'),
    (19, 'ko', '가스 확인',                  '가스 밸브 안전한지 확인'),
    (20, 'vi', 'Mặc đồng phục và tạp dề',   'Mặc tạp dề sạch và đeo găng tay'),
    (20, 'ko', '유니폼과 앞치마 착용',       '깨끗한 앞치마와 장갑 착용');

-- ---------------------------------------------------------------------------
-- Tasks: 10 per checklist (Zone 3 - Phục vụ)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO checklist_tasks (id, checklist_id, is_required, sort_order) VALUES
    (21, 3, 1, 1),  (22, 3, 1, 2),  (23, 3, 1, 3),  (24, 3, 1, 4),  (25, 3, 1, 5),
    (26, 3, 0, 6),  (27, 3, 1, 7),  (28, 3, 1, 8),  (29, 3, 0, 9),  (30, 3, 1, 10);

INSERT OR IGNORE INTO checklist_task_translations (task_id, language_code, title, description) VALUES
    (21, 'vi', 'Lau bàn ghế',               'Lau sạch tất cả bàn ghế trong khu vực'),
    (21, 'ko', '테이블 닦기',                '구역 내 모든 테이블과 의자 닦기'),
    (22, 'vi', 'Dọn dẹp sàn nhà',           'Quét và lau sàn khu vực phục vụ'),
    (22, 'ko', '바닥 청소',                  '홀 바닥 쓸고 닦기'),
    (23, 'vi', 'Kiểm tra thực đơn',         'Cập nhật bảng thực đơn hôm nay'),
    (23, 'ko', '메뉴판 확인',                '오늘의 메뉴판 업데이트'),
    (24, 'vi', 'Chuẩn bị dụng cụ ăn uống', 'Đếm và lau sạch bát đĩa, đũa thìa'),
    (24, 'ko', '식기 준비',                  '그릇, 접시, 젓가락 정리'),
    (25, 'vi', 'Bật nhạc và đèn',           'Bật nhạc nền và điều chỉnh đèn'),
    (25, 'ko', '음악과 조명 켜기',           '배경 음악 틀고 조명 조절'),
    (26, 'vi', 'Kiểm tra máy POS',          'Đảm bảo máy POS hoạt động'),
    (26, 'ko', 'POS 기기 확인',              'POS 기기 작동 확인'),
    (27, 'vi', 'Pha trà đá miễn phí',       'Pha sẵn bình trà đá cho khách'),
    (27, 'ko', '무료 차 준비',               '고객용 차 준비'),
    (28, 'vi', 'Kiểm tra WC',               'Đảm bảo WC sạch sẽ, đủ giấy'),
    (28, 'ko', '화장실 확인',                '화장실 청결, 휴지 충분한지 확인'),
    (29, 'vi', 'Sắp xếp menu trên bàn',    'Đặt thực đơn lên từng bàn'),
    (29, 'ko', '테이블 위에 메뉴 배치',      '각 테이블 위에 메뉴판 놓기'),
    (30, 'vi', 'Chào hỏi khách thân thiện', 'Sẵn sàng chào đón khách hàng'),
    (30, 'ko', '친절하게 고객 맞이',         '고객을 맞이할 준비');

-- ---------------------------------------------------------------------------
-- Tasks: 10 per checklist (Zone 4 - Kho)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO checklist_tasks (id, checklist_id, is_required, sort_order) VALUES
    (31, 4, 1, 1),  (32, 4, 1, 2),  (33, 4, 1, 3),  (34, 4, 1, 4),  (35, 4, 1, 5),
    (36, 4, 0, 6),  (37, 4, 1, 7),  (38, 4, 0, 8),  (39, 4, 1, 9),  (40, 4, 1, 10);

INSERT OR IGNORE INTO checklist_task_translations (task_id, language_code, title, description) VALUES
    (31, 'vi', 'Kiểm tra tồn kho',          'Đếm số lượng hàng tồn kho đầu ngày'),
    (31, 'ko', '재고 확인',                  '일일 재고 수량 확인'),
    (32, 'vi', 'Sắp xếp hàng hóa',         'Sắp xếp hàng theo loại và hạn sử dụng'),
    (32, 'ko', '상품 정리',                  '종류와 유통기한별로 정리'),
    (33, 'vi', 'Kiểm tra tủ đông',          'Đảm bảo nhiệt độ tủ đông ổn định'),
    (33, 'ko', '냉동고 확인',                '냉동고 온도 안정적인지 확인'),
    (34, 'vi', 'Nhận hàng mới',            'Kiểm tra và nhập hàng mới về'),
    (34, 'ko', '새 상품 입고',               '새로 온 상품 확인하고 입고'),
    (35, 'vi', 'Kiểm tra hạn sử dụng',      'Loại bỏ hàng hết hạn'),
    (35, 'ko', '유통기한 확인',              '유통기한 지난 상품 제거'),
    (36, 'vi', 'Dọn dẹp kho',              'Quét và lau sàn kho'),
    (36, 'ko', '창고 청소',                  '창고 바닥 쓸고 닦기'),
    (37, 'vi', 'Cập nhật sổ kho',          'Ghi chép hàng nhập - xuất trong ngày'),
    (37, 'ko', '재고장 업데이트',            '일일 입출고 기록'),
    (38, 'vi', 'Kiểm tra thiết bị',        'Đảm bảo kệ, xe đẩy hoạt động tốt'),
    (38, 'ko', '장비 확인',                  '선반, 카트 작동 양호 확인'),
    (39, 'vi', 'Báo cáo thiếu hàng',       'Liệt kê hàng cần đặt thêm'),
    (39, 'ko', '부족 상품 보고',             '추가 주문 필요한 상품 목록'),
    (40, 'vi', 'Khóa kho cẩn thận',        'Đảm bảo cửa kho đã khóa khi hết ca'),
    (40, 'ko', '창고 단단히 잠그기',         '근무 종료 시 창고 문 잠그기');

-- ---------------------------------------------------------------------------
-- Shift assignments for today + tomorrow (7 staff across 4 zones, 3 shifts)
-- Today
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO shift_assignments (id, shift_id, user_id, date, status) VALUES
    -- Morning shift (06:00-14:00)
    ( 1, 1, 1, strftime('%Y-%m-%d','now'),         'CONFIRMED'),  -- admin on morning (manager)
    ( 2, 1, 2, strftime('%Y-%m-%d','now'),         'CONFIRMED'),  -- nhanvien01 -> BEP_PHO
    ( 3, 1, 3, strftime('%Y-%m-%d','now'),         'CONFIRMED'),  -- nhanvien02 -> BEP_PHO
    ( 4, 1, 4, strftime('%Y-%m-%d','now'),         'CONFIRMED'),  -- nhanvien03 -> BUN_CHA
    ( 5, 1, 5, strftime('%Y-%m-%d','now'),         'CONFIRMED'),  -- nhanvien04 -> BUN_CHA
    -- Afternoon shift (14:00-22:00)
    ( 6, 2, 6, strftime('%Y-%m-%d','now'),         'SCHEDULED'),  -- nhanvien05 -> PHUC_VU
    ( 7, 2, 7, strftime('%Y-%m-%d','now'),         'SCHEDULED'),  -- nhanvien06 -> PHUC_VU
    -- Tomorrow morning
    ( 8, 1, 2, strftime('%Y-%m-%d','now','+1 day'), 'SCHEDULED'),
    ( 9, 1, 3, strftime('%Y-%m-%d','now','+1 day'), 'SCHEDULED'),
    (10, 1, 4, strftime('%Y-%m-%d','now','+1 day'), 'SCHEDULED');

-- ---------------------------------------------------------------------------
-- Zone assignments: link staff to current zone for today (morning shift)
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO zone_assignments (id, user_id, zone_id, assigned_by_user_id, reason, effective_from, is_current)
VALUES
    (1, 2, 1, 1, 'Auto-assigned from morning shift', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 1),
    (2, 3, 1, 1, 'Auto-assigned from morning shift', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 1),
    (3, 4, 2, 1, 'Auto-assigned from morning shift', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 1),
    (4, 5, 2, 1, 'Auto-assigned from morning shift', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 1);

-- ---------------------------------------------------------------------------
-- QR tokens: generate stable tokens for each zone (base32 random)
-- ---------------------------------------------------------------------------
UPDATE zones SET qr_token = 'ZONE_BEP_PHO_DEMO_TOKEN_001',   qr_generated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE code = 'BEP_PHO'   AND qr_token IS NULL;
UPDATE zones SET qr_token = 'ZONE_BUN_CHA_DEMO_TOKEN_002',   qr_generated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE code = 'BUN_CHA'   AND qr_token IS NULL;
UPDATE zones SET qr_token = 'ZONE_PHUC_VU_DEMO_TOKEN_003',   qr_generated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE code = 'PHUC_VU'   AND qr_token IS NULL;
UPDATE zones SET qr_token = 'ZONE_KHO_DEMO_TOKEN_004',       qr_generated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE code = 'KHO'       AND qr_token IS NULL;