-- PHASE 2: seed data
-- Idempotent enough for a fresh dev DB. Real production installer seeds
-- the same data programmatically so seed is repeatable.

-- ---------------------------------------------------------------------------
-- users
-- Passwords (BCrypt cost 12):
--   admin / admin123  -> $2a$12$wH8Q6JrYK1nT8u1pVqXJ5e2Vf4kD6uB6W7nF9oZq9hG6p4W1m0n3yS
--   nhanvien01 / staff123 -> $2a$12$T9zKz1hQ7aI5w4dY8cM5Ou1nQ8uH8xC0tE1rV5n3sB7oA6oP4wYp6K
-- These hashes are generated by the BCryptPasswordEncoder at runtime
-- during first-run bootstrap (see AdminBootstrap in PHASE 3) to keep the seed
-- reproducible. This migration only inserts the row skeletons; the bootstrap
-- step (in PHASE 3) writes the actual hashes.
-- ---------------------------------------------------------------------------
INSERT INTO users (username, password_hash, full_name, role, status, lang)
VALUES
    ('admin',     '__ADMIN_BCRYPT__',     'Quản trị viên',     'ADMIN', 'ACTIVE', 'vi'),
    ('nhanvien01', '__STAFF_BCRYPT__',    'Nhân viên 01',      'STAFF', 'ACTIVE', 'vi');

-- ---------------------------------------------------------------------------
-- categories + category_translations
-- ---------------------------------------------------------------------------
INSERT INTO categories (id, sort_order, status) VALUES
    (1, 1, 'ACTIVE'),
    (2, 2, 'ACTIVE'),
    (3, 3, 'ACTIVE'),
    (4, 4, 'ACTIVE'),
    (5, 5, 'ACTIVE');

INSERT INTO category_translations (category_id, language_code, name, description) VALUES
    (1, 'vi', 'Món chính',   'Các món ăn chính trong ngày'),
    (1, 'ko', '메인 요리',    '오늘의 메인 요리'),
    (2, 'vi', 'Món phụ',     'Món ăn kèm'),
    (2, 'ko', '사이드',       '함께 먹는 사이드'),
    (3, 'vi', 'Đồ uống',     'Nước uống các loại'),
    (3, 'ko', '음료',         '다양한 음료'),
    (4, 'vi', 'Combo',        'Combo tiết kiệm'),
    (4, 'ko', '콤보',         '저렴한 콤보'),
    (5, 'vi', 'Tráng miệng',  'Món ngọt cuối bữa'),
    (5, 'ko', '디저트',       '식후 달달한 디저트');

-- ---------------------------------------------------------------------------
-- foods (25 rows, mix of statuses and featured)
-- ---------------------------------------------------------------------------
INSERT INTO foods (id, category_id, price, status, is_featured, sort_order) VALUES
    -- Món chính (1)
    ( 1, 1, 75000,  'AVAILABLE', 1, 1),
    ( 2, 1, 65000,  'AVAILABLE', 1, 2),
    ( 3, 1, 80000,  'AVAILABLE', 0, 3),
    ( 4, 1, 70000,  'SOLD_OUT',  0, 4),
    ( 5, 1, 90000,  'AVAILABLE', 0, 5),
    ( 6, 1, 60000,  'HIDDEN',    0, 6),
    -- Món phụ (2)
    ( 7, 2, 25000,  'AVAILABLE', 1, 1),
    ( 8, 2, 30000,  'AVAILABLE', 0, 2),
    ( 9, 2, 20000,  'AVAILABLE', 0, 3),
    (10, 2, 28000,  'SOLD_OUT',  0, 4),
    (11, 2, 35000,  'HIDDEN',    0, 5),
    -- Đồ uống (3)
    (12, 3, 18000,  'AVAILABLE', 1, 1),
    (13, 3, 22000,  'AVAILABLE', 0, 2),
    (14, 3, 25000,  'AVAILABLE', 0, 3),
    (15, 3, 15000,  'SOLD_OUT',  0, 4),
    -- Combo (4)
    (16, 4, 120000, 'AVAILABLE', 1, 1),
    (17, 4, 135000, 'AVAILABLE', 0, 2),
    (18, 4, 99000,  'AVAILABLE', 0, 3),
    (19, 4, 110000, 'SOLD_OUT',  0, 4),
    -- Tráng miệng (5)
    (20, 5, 30000,  'AVAILABLE', 1, 1),
    (21, 5, 28000,  'AVAILABLE', 0, 2),
    (22, 5, 35000,  'HIDDEN',    0, 3),
    -- Bổ sung để đủ 25
    (23, 1, 85000,  'AVAILABLE', 0, 7),
    (24, 3, 20000,  'AVAILABLE', 0, 5),
    (25, 5, 32000,  'AVAILABLE', 0, 4);

-- food_translations: vi + ko cho mỗi food
INSERT INTO food_translations (food_id, language_code, name, description, ingredients, portion) VALUES
    ( 1, 'vi', 'Phở Bò Đặc Biệt',  'Phở bò truyền thống với nước dùng hầm xương 12 tiếng', 'Bánh phở, thịt bò, hành, ngò', '1 tô'),
    ( 1, 'ko', '스페셜 소고기 쌀국수', '12시간 우골 육수로 끓인 전통 쌀국수', '쌀국수, 소고기, 양파, 고수', '1그릇'),
    ( 2, 'vi', 'Bún Chả Hà Nội',   'Bún chả nướng than thơm lừng',                       'Bún, thịt heo nướng, nước mắm', '1 phần'),
    ( 2, 'ko', '하노이 분짜',        '숯에 구운 쌀국수와 돼지고기',                           '분, 돼지고기, 너겟', '1인분'),
    ( 3, 'vi', 'Cơm Tấm Sườn Bì',   'Cơm tấm sườn nướng, bì, chả',                       'Cơm tấm, sườn, bì, chả', '1 đĩa'),
    ( 3, 'ko', '카놈따 쨈 볶음덮밥',  '구운 갈비와 함께하는 쌀밥',                            '카놈따, 갈비, 껍데기', '1접시'),
    ( 4, 'vi', 'Bò Kho Bánh Mì',    'Bò kho với bánh mì giòn',                            'Thịt bò, bánh mì, sả', '1 phần'),
    ( 4, 'ko', '소고기 짜조 바게트',  '소고기 스튜와 바삭한 바게트',                          '소고기, 바게트, 레몬그라스', '1인분'),
    ( 5, 'vi', 'Lẩu Thái Hải Sản',  'Lẩu Thái chua cay với hải sản tươi',                 'Tôm, mực, cá, rau, nước lẩu', '1 nồi'),
    ( 5, 'ko', '태국식 해물 전골',    '매콤새콤한 태국식 해물 전골',                          '새우, 오징어, 생선, 채소', '1솥'),
    ( 6, 'vi', 'Gỏi Cuốn Tôm Thịt', 'Gỏi cuốn tươi với tôm và thịt',                      'Bánh tráng, tôm, thịt, rau', '4 cuốn'),
    ( 6, 'ko', '새우 돼지고기 쌀국수 만두', '신선한 새우와 돼지고기 만두',                       '쌀종이, 새우, 돼지고기, 채소', '4개'),
    ( 7, 'vi', 'Chả Giò Rế',        'Chả giò rế giòn truyền thống',                       'Thịt heo, miến, rau, bánh tráng', '4 cuốn'),
    ( 7, 'ko', '고기 춘권',           '바삭한 전통 춘권',                                    '돼지고기, 당면, 채소', '4개'),
    ( 8, 'vi', 'Khoai Tây Chiên',    'Khoai tây chiên giòn vàng',                          'Khoai tây, dầu, muối', '1 phần'),
    ( 8, 'ko', '감자튀김',            '바삭한 노란 감자튀김',                                '감자, 기름, 소금', '1인분'),
    ( 9, 'vi', 'Xà Lách Trộn Dầu Giấm', 'Salad rau trộn dầu giấm',                        'Xà lách, cà chua, dầu giấm', '1 đĩa'),
    ( 9, 'ko', '샐러드',              '식초 드레싱 샐러드',                                   '상추, 토마토, 드레싱', '1접시'),
    (10, 'vi', 'Bắp Xào Bơ',         'Bắp xào bơ thơm béo',                               'Bắp, bơ, đường', '1 phần'),
    (10, 'ko', '버터 옥수수',         '고소한 버터 옥수수',                                   '옥수수, 버터, 설탕', '1인분'),
    (11, 'vi', 'Bánh Hành',         'Bánh hành nướng',                                    'Hành, bột mì, dầu', '4 cái'),
    (11, 'ko', '파전',                '바삭한 파전',                                        '파, 밀가루, 기름', '4개'),
    (12, 'vi', 'Trà Đá',             'Trà đá truyền thống',                                'Trà, đá, đường', '1 ly'),
    (12, 'ko', '아이스 티',            '전통 아이스 티',                                     '차, 얼음, 설탕', '1잔'),
    (13, 'vi', 'Cà Phê Sữa Đá',     'Cà phê sữa đá Việt Nam',                             'Cà phê, sữa đặc, đá', '1 ly'),
    (13, 'ko', '베트남 아이스 커피',    '베트남식 연유 아이스 커피',                            '커피, 연유, 얼음', '1잔'),
    (14, 'vi', 'Nước Cam Tươi',      'Nước cam vắt tươi',                                  'Cam, đường, đá', '1 ly'),
    (14, 'ko', '생과일 주스',          '신선한 오렌지 주스',                                  '오렌지, 설탕, 얼음', '1잔'),
    (15, 'vi', 'Sinh Tố Bơ',          'Sinh tố bơ béo ngậy',                                'Bơ, sữa, đường, đá', '1 ly'),
    (15, 'ko', '아보카도 스무디',      '고소한 아보카도 스무디',                              '아보카도, 우유, 설탕, 얼음', '1잔'),
    (16, 'vi', 'Combo Gia Đình',     'Combo cho 4 người: phở + cơm + nước',                '4 món chính, 4 nước', '4 phần'),
    (16, 'ko', '패밀리 콤보',          '4인 가족 콤보: 쌀국수 + 밥 + 음료',                    '메인 4개, 음료 4개', '4인분'),
    (17, 'vi', 'Combo Cặp Đôi',      'Combo cho 2 người',                                  '2 món chính, 2 nước, 1 tráng miệng', '2 phần'),
    (17, 'ko', '커플 콤보',            '2인용 콤보',                                          '메인 2개, 음료 2개, 디저트 1개', '2인분'),
    (18, 'vi', 'Combo Tiết Kiệm',    'Combo 1 món chính + 1 nước',                         '1 món chính, 1 nước', '1 phần'),
    (18, 'ko', '베스트 콤보',          '메인 1개 + 음료 1개',                                  '메인 1개, 음료 1개', '1인분'),
    (19, 'vi', 'Combo Đặc Biệt',     'Combo 2 món chính + 2 nước + 1 tráng miệng',        '2 món chính, 2 nước, 1 tráng miệng', '1 phần'),
    (19, 'ko', '스페셜 콤보',          '메인 2개 + 음료 2개 + 디저트 1개',                     '메인 2개, 음료 2개, 디저트 1개', '1인분'),
    (20, 'vi', 'Chè Đậu Đỏ',         'Chè đậu đỏ thanh mát',                               'Đậu đỏ, nước cốt dừa, đường', '1 chén'),
    (20, 'ko', '팥죽',                '시원한 팥죽',                                          '팥, 코코넛 밀크, 설탕', '1그릇'),
    (21, 'vi', 'Bánh Flan',          'Bánh flan mềm mịn',                                  'Trứng, sữa, đường, caramel', '1 cái'),
    (21, 'ko', '플란',                '부드러운 푸딩',                                        '계란, 우유, 설탕, 캐러멜', '1개'),
    (22, 'vi', 'Kem Dừa',            'Kem dừa béo ngậy',                                   'Dừa, sữa, đường', '1 viên'),
    (22, 'ko', '코코넛 아이스크림',     '고소한 코코넛 아이스크림',                              '코코넛, 우유, 설탕', '1개'),
    (23, 'vi', 'Mì Quảng',           'Mì Quảng đặc sản miền Trung',                        'Mì Quảng, tôm, thịt, đậu phộng', '1 tô'),
    (23, 'ko', '미꽝 국수',            '중부 지역 특산 미꽝 국수',                              '미꽝, 새우, 돼지고기, 땅콩', '1그릇'),
    (24, 'vi', 'Trà Chanh',          'Trà chanh mát lạnh',                                 'Chanh, trà, đường, đá', '1 ly'),
    (24, 'ko', '레몬 티',              '시원한 레몬 티',                                      '레몬, 차, 설탕, 얼음', '1잔'),
    (25, 'vi', 'Bánh Chuối',         'Bánh chuối nướng',                                   'Chuối, bột, đường, dừa', '1 cái'),
    (25, 'ko', '바나나 빵',            '구운 바나나 빵',                                      '바나나, 밀가루, 설탕, 코코넛', '1개');

-- ---------------------------------------------------------------------------
-- store_settings (idempotent: row may already exist from a prior V1 deployment)
-- V3 also inserts this row, but V2 needs the row to exist now because the
-- store_translations INSERT below has a foreign key into store_settings(id).
-- ---------------------------------------------------------------------------
INSERT OR IGNORE INTO store_settings (id, logo_url, address, phone, opening_hours)
VALUES (1, NULL, NULL, NULL, NULL);

-- ---------------------------------------------------------------------------
-- store_translations
-- ---------------------------------------------------------------------------
INSERT INTO store_translations (store_id, language_code, store_name, description) VALUES
    (1, 'vi', 'Nhà hàng Mẫu', 'Cửa hàng mẫu dùng cho phát triển và demo.'),
    (1, 'ko', '샘플 식당',     '개발 및 데모용 샘플 매장입니다.');

-- ---------------------------------------------------------------------------
-- users: hashes sẽ được bootstrap ghi đè (BCrypt cost 12) trong PHASE 3.
-- Hai tài khoản mặc định:
--   admin / admin123
--   nhanvien01 / staff123
-- ---------------------------------------------------------------------------