package com.restaurant.staff.network

import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory

/**
 * Parses the QR payload generated by the server.
 *
 * The server's /api/server/info JSON is:
 *   { "server": "192.168.1.10", "port": 8080, "protocol": "http", "version": "1.0.0" }
 *
 * QR encoding is the same JSON. We accept either that JSON, or a URL like
 * `http://192.168.1.10:8080` for manual or third-party QR generators.
 */
object QrPayloadParser {

    @JsonClass(generateAdapter = true)
    data class QrPayload(
        val server: String,
        val port: Int,
        val protocol: String = "http",
        val version: String? = null
    )

    private val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
    private val adapter = moshi.adapter(QrPayload::class.java)

    fun parse(raw: String): QrPayload? {
        val trimmed = raw.trim()
        if (trimmed.isEmpty()) return null
        // Try JSON first
        runCatching { adapter.fromJson(trimmed) }
            .getOrNull()
            ?.let { return it }
        // Try URL
        val urlMatch = URL_REGEX.matchEntire(trimmed) ?: return null
        val host = urlMatch.groupValues[2]
        val portStr = urlMatch.groupValues[3]
        val protocol = urlMatch.groupValues[1].lowercase()
        val port = portStr.toIntOrNull() ?: return null
        return QrPayload(host, port, protocol)
    }

    private val URL_REGEX = Regex("""^(https?)://([^:/\s]+)(?::(\d+))?/?""")
}